routes/web.php
    <?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('index');



Auth::routes();

Route::group(['middleware'=> 'auth'],function(){
    
    Route::get('/admin', function () {
        return view('admin/index');
    })->name('admin');
    
    Route::get('/categories/{id}/delete','CategoryController@destroy')->name('categories.delete');
    Route::resource('categories', 'CategoryController');
    Route::post('/categories/search', 'CategoryController@search')->name('categories.search');
    
    Route::get('/products/{id}/delete', 'ProductController@destroy')->name('products.delete');
    Route::resource('products', 'ProductController'); 
    Route::post('/products/search', 'ProductController@search')->name('products.search');
});


Route::get('products/{id}','ProductController@show')->name('products.show');

Route::get('/telefonos/{subcategory}/show', 'TiendaController@showSubcat')->name('telefonos.subcategory');
Route::get('/telefonos','TiendaController@ShowAll')->name('telefonos');

Route::get('repuestos','TiendaController@showRepuestosAll')->name('repuestos.all');
Route::get('repuestos/{category}','TiendaController@showRepuestos')->name('repuestos.category');

Route::match(['post','get'],'/productos/buscar','TiendaController@buscarProductos')->name('buscar');
Route::get('/productos/{category}', 'TiendaController@showCat')->name('productos');

resources/views/admin/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div id="div-admin-buttons" class="row mt-3">
        <div class="col-3">
            <a href="{{route('categories.index')}}"><button class="btn btn-outline-dark">Categorias</button></a>
        </div>
        <div class="col-3">
            <a href="{{route('products.index')}}"><button class="btn btn-outline-dark">Productos</button></a>
        </div>
    </div>
</div>
@endsection