routes/web.php
    <?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('index');



Auth::routes();

Route::group(['middleware'=> 'auth'],function(){
    
    Route::get('/admin', function () {
        return view('admin/index');
    })->name('admin');
    
    Route::get('/categories/{id}/delete','CategoryController@destroy')->name('categories.delete');
    Route::resource('categories', 'CategoryController');
    Route::post('/categories/search', 'CategoryController@search')->name('categories.search');
    
    Route::get('/products/{id}/delete', 'ProductController@destroy')->name('products.delete');
    Route::resource('products', 'ProductController'); 
    Route::post('/products/search', 'ProductController@search')->name('products.search');
});


Route::get('products/{id}','ProductController@show')->name('products.show');

Route::get('/telefonos/{subcategory}/show', 'TiendaController@showSubcat')->name('telefonos.subcategory');
Route::get('/telefonos','TiendaController@ShowAll')->name('telefonos');

Route::get('repuestos','TiendaController@showRepuestosAll')->name('repuestos.all');
Route::get('repuestos/{category}','TiendaController@showRepuestos')->name('repuestos.category');

Route::match(['post','get'],'/productos/buscar','TiendaController@buscarProductos')->name('buscar');
Route::get('/productos/{category}', 'TiendaController@showCat')->name('productos');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\App;

class Product extends Model
{
    public $guarded = [];

    public function category()
    {
        return $this->belongsTo(Category::class, 'category_id', 'id');
    }

    public function subcategory()
    {
        return $this->belongsTo(Subcategory::class, 'subcategory_id', 'id');
    }

    public function color()
    {
        return $this->belongsTo(Color::class, 'colors_id', 'id');
    }

    public function imagen()
    {
        return $this->hasMany(Image::class);
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Color;
use App\Image;
use Illuminate\Http\Request;
use App\Product;
use App\Subcategory;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::all();
        $vac = compact('products');
        return view('admin.products.index',$vac);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        $subcategories = Subcategory::all();
        $vac = compact('categories','subcategories');
        return view('admin.products.create', $vac);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $destacado = false;
        $discount = false;
        $categoryRep = false;
        $stock = false;
        
        if ($request['category_repuestos']) {
            $categoryRep = $request['category_repuestos'];            
        }
        if(isset($request['destacado'])){
            $destacado = true;
        }
        if (isset($request['sale'])) {
            $discount = $this->discount($request);
        }
        if (isset($request['stock'])) {
            $stock = true;
        }
        $this->validator($request);
        $color = $this->createColor($request);
        
        $product = Product::create([
            'name'=>$request['name'],
            'stock'=>$stock,
            'price'=>$request['price'],
            'sale'=>$request['sale'],
            'discount'=>$discount,
        //     'image'=>$image,
            'description'=>$request['description'],
            'destacado'=>$destacado,
            'category_id'=>$request['category'],
            'colors_id'=>$color->id,
            'subcategory_id'=>$request['subcategory'],
            'categories_repuestos'=>$categoryRep,
        ]);
        $this->createImage($request, $product);

        return redirect()->route('products.index')->with('notice', 'El producto ha sido creado correctamente.');

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::find($id);
        $categories = Category::all();
        $subcategories = Subcategory::all();
        $vac = compact('product','categories','subcategories');
        return view('admin.products.edit',$vac);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $product = Product::find($id);
        
        $name = $product->name;
        if (isset($request['name'])) {
            $name = $request['name'];
        }

        $price = $product->price;
        if (isset($request['price'])) {
            $price = $request['price'];
        }

        $sale = $product->sale;
        if (isset($request['sale'])) {
            $sale = $request['sale'];
        }

        $discount = $product->discount;
        if (isset($request['sale'])) {
            $discount = $this->discount($request);
        }

        // $image = $product->image;
        // if(isset($request['img'])){
        //     $image = $this->createImage($request);   
        // }

        $description = $product->description;
        if (isset($request['description'])) {
            $description = $request['description'];
        }
        
        $color = $product->colors_id;
        if(isset($request['codigo'])){
            $color = $this->createColor($request);
        }

        $categoryRep = $product->categories_repuestos;
        if ($request['category_repuestos']) {
            $categoryRep = $request['category_repuestos'];
        }

        $stock = false;
        $destacado = false;
        $discount = false;

        if (isset($request['destacado'])) {
            $destacado = true;
        }

        if (isset($request['sale'])) {
            $discount = $this->discount($request);
        }

        if (isset($request['stock'])) {
            $stock = true;
        }
        
        $product->update([
            'name' => $name,
            'stock' => $stock,
            'price' => $price,
            'sale' => $sale,
            'discount' => $discount,
            // 'image' => $image,
            'description' => $description,
            'destacado' => $destacado,
            'category_id' => $request['category'],
            'colors_id' => $color->id,
            'subcategory_id'=>$request['subcategory'],
            'categories_repuestos'=>$categoryRep,
        ]);
        return redirect()->route('products.index')->with('notice', 'El producto ha sido editado correctamente.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product=Product::find($id);
        $product->delete();
        return redirect()->route('products.index')->with('notice', 'El producto ha sido eliminado correctamente.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $product = Product::find($id);
        $vac = compact('product');
        return view('show', $vac);
    }

    /**
     * @param  null|Request
     */
    public function search(Request $req)
    {
        if ($req['buscador']) {
            $products = Product::where('name', "like", "%" . $req['buscador'] . "%")->get();
            $vac = compact('products');
            return view('admin.products.results', $vac);
        }

        $products = Product::all();
        $vac = compact('products');
        return view('admin.products.results', $vac);
    }

    public function validator(Request $request)
    {
        $rules = [
            'name' => 'required|string|max:50',
            'price' => 'required|numeric',
            'description' => 'required|string|max:500',
            'codigo'=>'required'
        ];
        $message = [
            'required' => 'El campo es obligatorio',
            'unique' => 'El producto ya existe en nuestra base',
            'string' => 'El campo no puede estar vacio',
            'numeric' => 'Solo se admiten números',
        ];
        return $this->validate($request, $rules, $message);
    }

    public function createImage(Request $request, Product $product)
    {
        $position = 0;
        foreach ($request['img'] as $key) {
            $file = $key;
            $name = $request->input('name')."-".$request['name-color'].$position++.".".$file->extension();
            $path = $file->storeAs('products',$name, 'public');
            $image = Image::create([
                'name'=>$path,
                'product_id'=>$product->id,
            ]);
        }
        return $image;
    }

    public function createColor(Request $request)
    {
        $color = Color::create([
            'name'=>$request['name-color'],
            'codigo'=>$request['codigo'],
        ]);
        return $color;
    }

    public function discount(Request $request)
    {
      $price = $request['price'];
      $sale = $request['sale'];
      $resultado = ($price * $sale) / 100;
      $discount = $price - $resultado;
      return $discount; 
    }
}

resources/views/admin/products/create.blade.php
@extends('layouts.app')
@section('content')
<div class="col-12">
    <div class="col-12 text-center mb-5">
        <h2>Nuevo Producto</h2>
    </div>
    <form class="col-12 mx-auto" action="{{route('products.store')}}" method="post" enctype="multipart/form-data">
        @csrf
        <div class="form-row">
            <div id="name" class="form-group col-12 col-md-6 col-lg-3">
                <h4><label class="form-label" for="">Nombre</label></h4>
                <input name="name" class="form-control" type="text" value="{{ old('name') }}">
                <small id="passwordHelpBlock" class="form-text text-muted"><b>Nombre del nuevo producto</b></small>
                @error('name')
                <div id="error" class="alert alert-danger mx-auto col-12 col-sm-4 col-lg-12"><span>{{ $message }}</span></div>
                @enderror
            </div>
            <div id="category" class="form-group col-12 col-md-6 col-lg-3">
                <h4><label for="">Categoria</label></h4>
                <select class="form-control mb-1" name="category" value="{{ old('category') }}" id="">
                    <option value="">Elija una categoria</option>
                    @foreach($categories as $category)
                    <option value="{{$category->id}}">{{$category->name}}</option>
                    @endforeach
                </select>
                <small id="passwordHelpBlock" class="form-text text-muted"><b>Categoria a la que pertenece el producto</b></small>
                <a href="{{route('categories.create')}}"><button class="btn btn-outline-dark" type="button">Agregar Categoria</button></a>
                <small id="passwordHelpBlock" class="form-text text-muted"><b>Si no encuentra la categoria en el listado, agreguela</b></small>
                @error('category_id')
                <div id="error" class="alert alert-danger mx-auto col-11 col-sm-4 col-lg-12"><span>{{ $message }}</span></div>
                @enderror
            </div>
            <div id="subcategory" class="form-group col-12 col-md-6 col-lg-3">
                <h4><label for="">SubCategoria</label></h4>
                <select class="form-control mb-1" name="subcategory" value="{{ old('subcategory') }}" id="">
                    <option value="">Elija una Subcategoria</option>
                    @foreach($subcategories as $subcategory)
                    <option value="{{$subcategory->id}}">{{$subcategory->name}}</option>
                    @endforeach
                </select>
                <small id="passwordHelpBlock" class="form-text text-muted"><b>Solo para telefonos</b></small>
            </div>
            <div id="category_repuestos" class="form-group col-12 col-md-6 col-lg-3">
                <h4><label for="">Categoria Repuestos</label></h4>
                <select class="form-control mb-1" name="category_repuestos" value="" id="">
                    <option value="">Elija una Categoria de repuesto</option>
                    <option value="modulos">Modulos</option>
                    <option value="baterias">Baterias</option>
                    <option value="pinDeCarga">Pin de Carga</option>
                    <option value="camaras">Camaras</option>
                    <option value="carcasas">Carcasas</option>
                </select>
                <small id="passwordHelpBlock" class="form-text text-muted"><b>Solo para Respuestos</b></small>
            </div>
            <div id="price" class="form-group col-12 col-md-6 col-lg-3">
                <h4><label for="">Precio</label></h4>
                <input name="price" class="form-control" type="number" value="{{ old('price') }}">
                <small id="passwordHelpBlock" class="form-text text-muted"><b>Precio del producto Ej: 10500,50</b></small>
                @error('price')
                <div id="error" class="alert alert-danger mx-auto col-11 col-sm-4 col-lg-12"><span>{{ $message }}</span></div>
                @enderror
            </div>
            <div id="discount" class="form-group col-12 col-md-6 col-lg-3">
                <h4><label for="">Descuento</label></h4>
                <input name="sale" class="form-control" type="number" value="{{ old('sale') }}">
                <small id="passwordHelpBlock" class="form-text text-muted"><b>Solo poner el numero que corresponde al % Ej: 25</b></small>
                @error('sale')
                <div id="error" class="alert alert-danger mx-auto col-11 col-sm-4 col-lg-12"><span>{{ $message }}</span></div>
                @enderror
            </div>
            <div id="div-color" class="form-group col-12 col-md-6 col-lg-3">
                <h4><label for="">Color</label></h4>
                <input class="" id="input-color" name="codigo" onchange="getColorName()" type="color" value="">
                <input id="input-name-color" name="name-color" value="Black" readonly></input>
                <small id="passwordHelpBlock" class="form-text text-muted"><b>Elija un color para el producto</b></small>
                @error('color')
                <div id="error" class="alert alert-danger mx-auto col-11 col-sm-4 col-lg-12"><span>{{ $message }}</span></div>
                @enderror
            </div>
            <div id="image" class="form-group col-12 col-md-6 col-lg-3">
                <h4><label for="">Imagen</label></h4>
                <input name="img[]" multiple  class="form-control-file" type="file">
                <small id="passwordHelpBlock" class="form-text text-muted"><b>Elija una imagen para su producto</b></small><br>
                @error('image')
                <div id="error" class="alert alert-danger mx-auto col-11 col-sm-4 col-lg-12"><span>{{ $message }}</span></div>
                @enderror
            </div>
            <div id="extras" class="form-gruop col-12 col-md-6 col-lg-3">
                <h4><label for="">Extras</label></h4>
                <div class="form-check">
                    <input name="destacado" class="mt-1 mr-1" type="checkbox" value="si">
                    <label for="">Producto destacado</label>
                </div>
                <div class="form-check">
                    <input name="stock" class="mt-1 mr-1" type="checkbox" value="si">
                    <label for="">Stock</label>
                </div>
            </div>
            <div id="description" class="form-group col-12 col-md-6 col-lg-3">
                <h4><label class="" for="">Descripcion</label></h4>
                <textarea class="form-control" name="description" maxlength="300" cols="30" rows="5" onkeyup="countChars(this);" placeholder="Maximo 300 caracteres" value="{{ old('description') }}"></textarea>
                <p id="charNum">300 caracteres restantes</p>
                @error('description')
                <div id="error" class="alert alert-danger mx-auto col-11 col-sm-4 col-lg-12"><span>{{ $message }}</span></div>
                @enderror
            </div>
        </div>
        <div id="buttons" class="text-center col-12">
            <button class="mx-2 btn btn-outline-dark" type="submit">Agregar</button>
            <a href="{{route('products.index')}}"><button class="btn btn-outline-dark" type="button">Cancelar</button></a>
        </div>
    </form>
</div>
@endsection

resources/views/admin/products/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="col-12">
    <div class="col-12 text-center mb-5">
        <h2>Modificar Producto</h2>
    </div>
    <form class="col-12 mx-auto" action="{{route('products.update',['product'=>$product])}}" method="post" enctype="multipart/form-data">
        @method('PUT')
        @csrf
        <div class="form-row">
            <div id="name" class="form-group col-12 col-md-6 col-lg-3">
                <h4><label class="form-label" for="">Nombre</label></h4>
                <input name="name" class="form-control" type="text" value="{{ $product->name }}">
                <small id="passwordHelpBlock" class="form-text text-muted"><b>Nombre del nuevo producto</b></small>
                @error('name')
                <div id="error" class="alert alert-danger mx-auto col-12 col-sm-4 col-lg-12"><span>{{ $message }}</span></div>
                @enderror
            </div>
            <div id="category" class="form-group col-12 col-md-6 col-lg-3">
                <h4><label for="">Categoria</label></h4>
                <select class="form-control mb-1" name="category" value="{{ $product->category->name }}" id="">
                    <option value="">Elija una categoria</option>
                    @foreach($categories as $category)
                    <option <?php if ($category->id == $product->category_id) echo "selected"; ?> value="{{$category->id}}">{{$category->name}}</option>
                    @endforeach
                </select>
                <small id="passwordHelpBlock" class="form-text text-muted"><b>Categoria a la que pertenece el producto</b></small>
                <a href="{{route('categories.create')}}"><button class="btn btn-outline-dark" type="button">Agregar Categoria</button></a>
                <small id="passwordHelpBlock" class="form-text text-muted"><b>Si no encuentra la categoria en el listado, agreguela</b></small>
                @error('category_id')
                <div id="error" class="alert alert-danger mx-auto col-11 col-sm-4 col-lg-12"><span>{{ $message }}</span></div>
                @enderror
            </div>
            <div id="subcategory" class="form-group col-12 col-md-6 col-lg-3">
                <h4><label for="">Subcategoria</label></h4>
                <select class="form-control mb-1" name="subcategory" value="" id="">
                    <option value="">Elija una subcategoria</option>
                    @if($subcategories)
                    @foreach($subcategories as $subcategory)
                    <option <?php if ($subcategory->id == $product->subcategory_id) echo "selected"; ?> value="{{$subcategory->id}}">{{$subcategory->name}}</option>
                    @endforeach
                    @else
                    <option value="{{$subcategory->id}}">{{$subcategory->name}}</option>
                    @endif
                </select>
                <small id="passwordHelpBlock" class="form-text text-muted"><b>Solo para telefonos</b></small>
                @error('subcategory_id')
                <div id="error" class="alert alert-danger mx-auto col-11 col-sm-4 col-lg-12"><span>{{ $message }}</span></div>
                @enderror
            </div>
            <div id="category_repuestos" class="form-group col-12 col-md-6 col-lg-3">
                <h4><label for="">Categoria Repuestos</label></h4>
                <select class="form-control mb-1" name="category_repuestos" value="" id="">
                    <option value="">Elija una Categoria de repuesto</option>
                    <option <?php if ($product->categories_repuestos == "modulos") echo "selected"; ?> value="modulos">Modulos</option>
                    <option <?php if ($product->categories_repuestos == "baterias") echo "selected"; ?> value="baterias">Baterias</option>
                    <option <?php if ($product->categories_repuestos == "pin de carga") echo "selected"; ?> value="pin de carga">Pin de Carga</option>
                    <option <?php if ($product->categories_repuestos == "camaras") echo "selected"; ?> value="camaras">Camaras</option>
                    <option <?php if ($product->categories_repuestos == "carcasas") echo "selected"; ?> value="carcasas">Carcasas</option>
                </select>
                <small id="passwordHelpBlock" class="form-text text-muted"><b>Solo para Respuestos</b></small>
            </div>
            <div id="price" class="form-group col-12 col-md-6 col-lg-3">
                <h4><label for="">Precio</label></h4>
                <input name="price" class="form-control" type="number" value="{{ $product->price }}">
                <small id="passwordHelpBlock" class="form-text text-muted"><b>Precio del producto Ej: 10500,50</b></small>
                @error('price')
                <div id="error" class="alert alert-danger mx-auto col-11 col-sm-4 col-lg-12"><span>{{ $message }}</span></div>
                @enderror
            </div>
            <div id="discount" class="form-group col-12 col-md-6 col-lg-3">
                <h4><label for="">Descuento</label></h4>
                <input name="sale" class="form-control" type="number" value="{{ $product->sale }}">
                <small id="passwordHelpBlock" class="form-text text-muted"><b>Solo poner el numero que corresponde al % Ej: 25</b></small>
                @error('sale')
                <div id="error" class="alert alert-danger mx-auto col-11 col-sm-4 col-lg-12"><span>{{ $message }}</span></div>
                @enderror
            </div>
            <div id="div-color" class="form-group col-12 col-md-6 col-lg-3">
                <h4><label for="">Color</label></h4>
                <input class="" id="input-color" name="codigo" onchange="getColorName()" type="color" value="{{ $product->color->codigo }}">
                <input id="input-name-color" name="name-color" value="{{$product->color->name}}" readonly></input>
                <small id="passwordHelpBlock" class="form-text text-muted"><b>Elija un color para el producto</b></small>
                @error('color')
                <div id="error" class="alert alert-danger mx-auto col-11 col-sm-4 col-lg-12"><span>{{ $message }}</span></div>
                @enderror
            </div>
            <div id="image" class="form-group col-12 col-md-6 col-lg-3">
                <h4><label for="">Imagen</label></h4>
                <input name="img[]" multiple class="form-control-file" type="file">
                <small id="passwordHelpBlock" class="form-text text-muted"><b>Elija una imagen para su producto</b></small><br>
                @error('image')
                <div id="error" class="alert alert-danger mx-auto col-11 col-sm-4 col-lg-12"><span>{{ $message }}</span></div>
                @enderror
            </div>
            <div id="extras" class="form-gruop col-12 col-md-6 col-lg-3">
                <h4><label for="">Extras</label></h4>
                <div class="form-check">
                    @if($product->destacado)
                    <input name="destacado" class="mt-1 mr-1" type="checkbox" checked value="si">
                    <label for="">Producto destacado</label><br>
                    @else
                    <input name="destacado" class="mt-1 mr-1" type="checkbox" value="si">
                    <label for="">Producto destacado</label><br>
                    @endif
                </div>
                <div class="form-check">
                    @if($product->destacado)
                    <input name="stock" class="mt-1 mr-1" type="checkbox" checked value="si">
                    <label for="">Stock</label>
                    @else
                    <input name="stock" class="mt-1 mr-1" type="checkbox" value="si">
                    <label for="">Stock</label>
                    @endif
                </div>
            </div>
            <div id="description" class="form-group col-12 col-md-6 col-lg-3">
                <h4><label class="" for="">Descripcion</label></h4>
                <textarea class="form-control" name="description" maxlength="300" cols="30" rows="5" onkeyup="countChars(this);">{{$product->description}}</textarea>
                <p id="charNum">300 caracteres restantes</p>
                @error('description')
                <div id="error" class="alert alert-danger mx-auto col-11 col-sm-4 col-lg-12"><span>{{ $message }}</span></div>
                @enderror
            </div>
        </div>
        <div id="buttons" class="text-center col-12">
            <button class="mx-2 btn btn-outline-dark" type="submit">Modificar</button>
            <a href="{{route('products.index')}}"><button class="btn btn-outline-dark" type="button">Cancelar</button></a>
        </div>
    </form>
</div>
@endsection

resources/views/admin/products/index.blade.php
@extends('layouts.app')
@section('content')
<div id="div-all-prod" class="col-12">
    <div id="div-tit-prod" class="col-12">
        <h2>Productos</h2>
        <a href="{{route('admin')}}" style="text-decoration: none; color:black"><i class="fas fa-arrow-circle-left"></i> Volver</a>
    </div>
    <div id="div-opc-prod" class="row mx-auto mb-3 col-12 col-md-8 col-lg-6 col-xl-4">
        <div id="div-but-new-index-product" class="my-3 col-6 col-md-4">
            <a href="{{route('products.create')}}"><button class="btn btn-outline-dark w-100">Nuevo</button></a>
        </div>
        <form class="input-group input-group-sm my-auto mb-3 col-12 col-md-6" action="{{route('products.search')}}" method="post">
            @csrf
            <div class="input-group-prepend">
                <button class="input-group-text" id="inputGroup-sizing-sm">Buscar</button>
            </div>
            <input type="text" class="form-control" aria-label="Small" aria-describedby="inputGroup-sizing-sm">
        </form>
    </div>
    <div class="my-2 col-12 text-center">
        @if(Session::has('notice'))
        <h3 class="my-auto text-success"><strong>{{ Session::get('notice') }}</strong></h3>
        @endif
    </div>
</div>
<div class="table" style="overflow-x:auto;">
    <table class="mx-auto">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nombre</th>
                <th scope="col">Stock</th>
                <th scope="col">Precio</th>
                <th scope="col">Descuento</th>
                <th scope="col">Destacado</th>
                <th scope="col">Categoria</th>
                <th scope="col">Subcategoria</th>
                <th scope="col">Categoria repuesto</th>
                <th scope="col">Descripcion</th>
                <th scope="col">Color</th>
                <th scope="col">Imagen</th>
                <th scope="col" colspan="2">Opciones</th>
            </tr>
        </thead>
        <tbody>
            @foreach($products as $product => $data)
            <tr>
                <th scope="row">{{$data->id}}</th>
                <th class="text-center">{{$data->name}}</th>
                @if ($data->stock)
                <th class="text-center">Si</th>
                @else
                <th class="text-center">No</th>
                @endif
                <th class="text-center">{{$data->price}}</th>
                @if($data->sale)
                <th class="text-center">{{$data->sale}}%</th>
                @else
                <th class="text-center">No tiene</th>
                @endif
                @if($data->destacado)
                <th class="text-center">Si</th>
                @else
                <th class="text-center">No</th>
                @endif
                <th class="text-center">{{$data->category->name}}</th>
                @if($data->subcategory)
                <th class="text-center">{{$data->subcategory->name}}</th>
                @else
                <th class="text-center">No tiene</th>
                @endif
                @if($data->categories_repuestos)
                <th class="text-center">{{$data->categories_repuestos}}</th>
                @else
                <th class="text-center">No tiene</th>
                @endif
                <th class="text-center">{{Str::limit($data->description,20)}}</th>
                <th class="text-center">{{$data->color->name}}</th>
                <th id="th-index-product" class="text-center"><img id="img-product" src="{{asset('storage/'.$data->image)}}" alt="imagen de: {{$data->name}}"></th>
                <th><a href="{{route('products.edit',['product'=>$data->id])}}"><i class="far fa-edit" title="editar"></i></a></th>
                <th><a href="{{route('products.delete',['id'=>$data->id])}}"><i class="far fa-trash-alt" title="borrar"></i></a></th>
            </tr>
            @endforeach
        </tbody>
    </table>
</div>
@endsection