routes/web.php
    <?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('index');



Auth::routes();

Route::group(['middleware'=> 'auth'],function(){
    
    Route::get('/admin', function () {
        return view('admin/index');
    })->name('admin');
    
    Route::get('/categories/{id}/delete','CategoryController@destroy')->name('categories.delete');
    Route::resource('categories', 'CategoryController');
    Route::post('/categories/search', 'CategoryController@search')->name('categories.search');
    
    Route::get('/products/{id}/delete', 'ProductController@destroy')->name('products.delete');
    Route::resource('products', 'ProductController'); 
    Route::post('/products/search', 'ProductController@search')->name('products.search');
});


Route::get('products/{id}','ProductController@show')->name('products.show');

Route::get('/telefonos/{subcategory}/show', 'TiendaController@showSubcat')->name('telefonos.subcategory');
Route::get('/telefonos','TiendaController@ShowAll')->name('telefonos');

Route::get('repuestos','TiendaController@showRepuestosAll')->name('repuestos.all');
Route::get('repuestos/{category}','TiendaController@showRepuestos')->name('repuestos.category');

Route::match(['post','get'],'/productos/buscar','TiendaController@buscarProductos')->name('buscar');
Route::get('/productos/{category}', 'TiendaController@showCat')->name('productos');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    public $guarded = [];

    public function products()
    {
        return $this->hasMany(Product::class, 'category_id');
    }

    // public function subcategory(){
    //     return $this->belongsTo(Subcategory::class);
    // }

    public function subcategories()
    {
        return $this->hasMany(Subcategory::class, 'category_id');
    }

}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;
class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories=Category::all();
        $vac=compact('categories');
        return view('admin.categories.index',$vac);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.categories.create');
    }
   
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validator($request);
        Category::create([
            'name'=>$request['name'],
            'description'=>$request['description']
        ]);
        return redirect()->route('categories.index')->with('notice', 'La categoria ha sido creada correctamente');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::find($id);
        $vac = compact('category');
        return view('admin.categories.edit',$vac);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validator($request);
        $category=Category::find($id);
        $category->update([
            'name'=>$request->input('name'),
            'description'=>$request->input('description')
        ]); 
        return redirect()->route('categories.index')->with('notice', 'La categoria ha sido editada correctamente');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {   

        $category=Category::find($id);
        var_dump($category);
        $category->delete();
        return redirect()->route('categories.index')->with('notice', 'La categoria ha sido eliminada correctamente');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $category = Category::find($id);
        $vac = compact('category');
        return view('admin.categories.show', $vac);
    }

    /**
     * @param  null|Request
     */
    public function search(Request $req)
    {
        if($req['buscador']){
            $categories = Category::where('name', "like", "%" . $req['buscador'] . "%")->get();
            $vac = compact('categories');
            return view('admin.categories.results',$vac);
        }
        
        $categories = Category::all();
        $vac = compact('categories');
        return view('admin.categories.results', $vac);
    }
    
    public function validator(Request $request)
    {
        $rules = [
            'name' => 'required|unique:categories|string|max:50',
            'description' => 'required|string|max:300'
        ];
        $message = [
            'required' => 'El campo es obligatorio.',
            'unique' => 'La categoria ya existe en nuestra base.',
            'string' => 'Solo se admiten letras.'
        ];
        return $this->validate($request, $rules, $message);
    }
}

resources/views/admin/categories/create.blade.php
@extends('layouts.app')
@section('content')
<div class="col-12">
    <div class="text-center col-12">
        <h2>Nueva Categoria</h2>
    </div>
    <form class="col-12 text-center mx-auto" action="{{route('categories.store')}}" method="post">
        @csrf
        <div class="mb-3 col-12">
            <div class="col-12">
                <h4><label for="">Nombre</label></h4>
            </div>
            <input name="name" class="" type="text">
            @error('name')
            <div id="error" class="alert alert-danger mx-auto col-11 col-sm-4 col-lg-12"><span>{{ $message }}</span></div>
            @enderror
        </div>
        <div class="mb-3 col-12">
            <div class="col-12">
                <h4><label class="" for="">Descripcion</label></h4>
            </div>
            <textarea class="" name="description" maxlength="300" cols="30" rows="5" onkeyup="countChars(this);" placeholder="Maximo 300 caracteres"></textarea>
            <p id="charNum">300 caracteres restantes</p>
            @error('description')
            <div id="error" class="alert alert-danger mx-auto col-11 col-sm-4 col-lg-12"><span>{{ $message }}</span></div>
            @enderror
        </div>
        <div class="col-12">
            <button class="mx-2 btn btn-outline-dark" type="submit">Agregar</button>
            <a href="{{route('categories.index')}}"><button class="btn btn-outline-dark" type="button">Cancelar</button></a>
        </div>
    </form>
</div>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="row">
    <div class="col-12">
        <div class="text-center col-12">
            <h2>Editar Categoria</h2>
        </div>
        <form class="col-12 text-center mx-auto" action="{{route('categories.update',['category'=>$category])}}" method="POST">
            @method('PUT')
            @csrf
            <div class="mb-3 col-12">
                <div class="col-12">
                    <h4><label for="">Nombre</label></h4>
                </div>
                <input type="text" name="name" value="{{$category->name}}">
                @error('name')
                <div id="error" class="alert alert-danger mx-auto col-11 col-sm-4 col-lg-3 mt-2"><span>{{ $message }}</span></div>
                @enderror
            </div>
            <div id="" class="mb-3 col-12">
                <div class="col-12">
                    <h4><label for="">Descripcion</label></h4>
                </div>
                <textarea name="description" id="" cols="30" rows="5" value="">{{$category->description}}</textarea>
                @error('description')
                <div id="error" class="alert alert-danger mx-auto col-11 col-sm-4 col-lg-3 mt-2"><span>{{ $message }}</span></div>
                @enderror
            </div>
            <div class="mx-auto col-4">
                <button class="btn btn-outline-dark" type="submit">Editar</button>
                <a href="{{route('categories.index')}}"><button class="btn btn-outline-dark" type="button">Cancelar</button></a>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/admin/categories/index.blade.php
@extends('layouts.app')
@section('content')
<div id="div-all-cat" class="col-12">
    <div id="div-tit-cat" class="col-12">
        <h2>Categorias</h2>
        <a href="{{route('admin')}}" style="text-decoration: none; color:black"><i class="fas fa-arrow-circle-left"></i> Volver</a>
    </div>
    <div id="div-opc-cat" class="row mx-auto mb-3 col-12 col-md-8 col-lg-6 col-xl-4">
        <div class="my-3 col-6 col-md-4">
            <a href="{{route('categories.create')}}"><button class="btn btn-outline-dark w-100">Nueva</button></a>
        </div>
        <form class="input-group input-group-sm mb-5 my-auto col-12 col-md-6" action="{{route('categories.search')}}" method="post">
            @csrf
            <div class="input-group-prepend">
                <button class="input-group-text" id="inputGroup-sizing-sm">Buscar</button>
            </div>
            <input type="text" class="form-control" aria-label="Small" aria-describedby="inputGroup-sizing-sm">
        </form>
    </div>
    <div class="my-2 col-12 text-center">
        @if(Session::has('notice'))
        <h3 class="my-auto text-success"><strong>{{ Session::get('notice') }}</strong></h3>
        @endif
    </div>
</div>
<div class="table" style="overflow-x:auto;">
    <table class="mx-auto">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nombre</th>
                <th scope="col">Descripcion</th>
                <th scope="col" colspan="2">Opciones</th>
            </tr>
        </thead>
        <tbody>
            @foreach($categories as $category => $data)
            <tr>
                <th scope="row">{{$data->id}}</th>
                <th>{{$data->name}}</th>
                <th>{{$data->description}}</th>
                <th><a href="{{route('categories.edit',['category'=>$data])}}"><i class="far fa-edit" title="editar"></i></a></th>
                <th><a href="{{route('categories.delete',['id'=>$data->id])}}"><i class="far fa-trash-alt" title="borrar"></i></a></th>
            </tr>
            @endforeach
        </tbody>
    </table>
</div>
@endsection

resources/views/admin/categories/results.blade.php
@extends('layouts.app')
@section('content')
<div id="div-results-cat" class="col-12">
    <div id="div-tit-cat" class="col-12">
        <h2 class="">Resultados de busqueda</h2>
    </div>
    <div id="div-cancel-cat" class="row mx-auto mb-3 col-12 col-md-8 col-lg-6 col-xl-4">
        <form class="input-group input-group-sm mb-3 mt-1 col-12 col-md-6" action="{{route('categories.search')}}" method="post">
            @csrf
            <div class="input-group-prepend">
                <button class="input-group-text" id="inputGroup-sizing-sm">Buscar</button>
            </div>
            <input type="text" class="form-control" aria-label="Small" aria-describedby="inputGroup-sizing-sm">
        </form>
        <div class="col-12 col-md-4">
            <a href="{{route('categories.index')}}"><button class="btn btn-outline-dark w-100">Volver</button></a>
        </div>
    </div>
    <div class="table" style="overflow-x:auto;">
        <table class="mx-auto">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Nombre</th>
                    <th scope="col">Descripcion</th>
                    <th scope="col" colspan="2">Opciones</th>
                </tr>
            </thead>
            <tbody>
                @foreach($categories as $category => $data)
                <tr>
                    <th scope="row">{{$data->id}}</th>
                    <th>{{$data->name}}</th>
                    <th>{{$data->description}}</th>
                    <th><a href="{{route('categories.edit',['category'=>$data])}}"><i class="far fa-edit" title="editar"></i></a></th>
                    <th><a href="{{route('categories.delete',['id'=>$data->id])}}" data-method="delete"><i class="far fa-trash-alt" title="borrar"></i></a></th>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>
@endsection